repos:
- repo: local
  hooks:
  - id: isort
    name: Run isort
    types: [python]
    exclude: ^tests/
    entry: isort
    language: system
  - id: black
    name: Run black
    types: [python]
    exclude: ^tests/
    entry: black
    language: system
    args: ["--line-length=100"]
  - id: pydocstyle
    name: Roda pydocstyle
    types: [python]
    exclude: ^tests/
    entry: pydocstyle
    language: system
  - id: pylint
    name: Roda pylint
    types: [python]
    exclude: ^tests/
    entry: pylint
    language: system
  - id: pytest
    name: Roda pytest
    entry: bash -c "PYTHONPATH=. python -m pytest"
    language: system
    pass_filenames: false
    always_run: true
