{
 "title": "DRIFT-MODELO",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Monitoração Drift do Modelo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Concept Drift Score:",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "concept_drift_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "F1  Score:",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_f1_score_production", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Acurácia Modelo em Produção:",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_accuracy_score_production",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recall:",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_recall_score_production", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Precision Score:",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_precision_score_production",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QTD de Verificação de Drift:",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_drift_checks_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Concept Drift Score:",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "concept_drift_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "F1  Score:",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 17 },
   "targets": [
    { "expr": "model_f1_score_production", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recall:",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 22 },
   "targets": [
    { "expr": "model_recall_score_production", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Drift Score:",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 19, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "data_drift_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latência Média Cálculo do Drif (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(drift_calculation_duration_seconds_sum[5m]) / rate(drift_calculation_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Métricas /feedback", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Taxa de Requisições /feedback (por segundo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(drift_http_requests_total{method=\"POST\", endpoint=\"/feedback\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Tempo Médio de Resposta /predict (POST)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(drift_http_request_duration_seconds_sum{endpoint=\"/feedback\", method=\"POST\"}[5m])) by (endpoint) / sum(rate(drift_http_request_duration_seconds_count{endpoint=\"/feedback\", method=\"POST\"}[5m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Métricas HTTP Totais", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Taxa de Requisições (por segundo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(drift_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Tempo Médio de Resposta HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(drift_http_request_duration_seconds_sum[5m])) / sum by(endpoint) (rate(drift_http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "taxa de erros 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(drif_http_requests_total{status_code=\"500\", endpoint=\"/feedback\"}[5m])) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentagem de Erros 5xx:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (endpoint) (rate(drift_http_requests_total{status_code=~\"5..\", endpoint=\"/predict\"}[5m]))\r\n/\r\nsum by (endpoint) (rate(drift_http_requests_total{endpoint=\"/predict\"}[5m]))\r\n* 100) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}