{
 "title": "API-DECISION",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Métricas de Previsões", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Versão do Modelo:",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total de Previsões (Sucesso)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "successful_predictions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QTD. Previsões com Falha:",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prediction_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Taxa de Previsões (por minuto)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(successful_predictions_total[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa Erros de Previsão (por minuto)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "rate(prediction_errors_total[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência Média de Previsão (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prediction_duration_seconds_sum[5m]) / rate(prediction_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência de Previsão p95 (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prediction_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Métricas predict/", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Taxa de Requisições /predict (por segundo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{method=\"POST\", endpoint=\"/predict\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Tempo Médio de Resposta /predict (POST)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"/predict\", method=\"POST\"}[5m])) by (endpoint) / sum(rate(http_request_duration_seconds_count{endpoint=\"/predict\", method=\"POST\"}[5m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Métricas HTTP Totais", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Taxa de Requisições (por segundo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": " Tempo Médio de Resposta HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(http_request_duration_seconds_sum[5m])) / sum by(endpoint) (rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "taxa de erros 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_total{status_code=\"500\", endpoint=\"/predict\"}[5m])) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentagem de Erros 5xx:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (endpoint) (rate(http_requests_total{status_code=~\"5..\", endpoint=\"/predict\"}[5m]))\r\n/\r\nsum by (endpoint) (rate(http_requests_total{endpoint=\"/predict\"}[5m]))\r\n* 100) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}